# Generated by Django 3.0.5 on 2020-04-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Serieseses'},
        ),
        migrations.AlterModelOptions(
            name='seriespost',
            options={'ordering': ('srt',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='summary',
        ),
    ]
