# Generated by Django 3.0.5 on 2020-05-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=models.BooleanField(default=False),
        ),
    ]
