# Generated by Django 3.0.5 on 2020-06-14 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200516_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
