# Generated by Django 3.0.7 on 2021-03-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='google_doc_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
