# Generated by Django 3.0.7 on 2021-03-21 00:31

from django.db import migrations, models
import django.db.models.deletion
from django.db import connections


def convert_to_innodb(apps, schema_editor):

    cursor = connections["default"].cursor()

    cursor.execute("SHOW TABLE STATUS")

    for row in cursor.fetchall():
        if row[1] != "InnoDB":
            print("Converting %s" % row[0]),
            print(cursor.execute("ALTER TABLE %s ENGINE=INNODB" % row[0]))


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_series_slug'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_innodb, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pub', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='options', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('text', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('pub', models.BooleanField(default=True)),
                ('survey_option', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.SurveyOption')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='post',
            name='survey_allows_custom_answers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='survey_closed_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='survey_open_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
