# Generated by Django 3.0.7 on 2021-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210320_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyoption',
            name='custom',
            field=models.BooleanField(default=True),
        ),
    ]
