# Generated by Django 3.0.7 on 2021-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_surveyoption_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyoption',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
